### ISSUE TITLE
Please support the new devices released at the 2019 September device.

### ISSUE THREAD

**Issue by OkiRules** [devicekit/DeviceKit#199]
Please support:

- iPhone 11
- iPhone 11 Pro
- iPhone 11 Pro Max
- The new iPad (10.2 inch - not sure what it's called) - [iPad 10.2](https://www.apple.com/ipad-10.2)

You can see here the new devices here: [Apple](https://www.apple.com)

Thanks!

**Comment by Zandor300** [comment]
I already had made some commits for this in a separate branch but hadn't created the pull request for it yet. Here is the pull request now: https://github.com/devicekit/DeviceKit/pull/200

It is still draft since we don't have the identifiers for the devices yet and the automatic detection won't work yet. (`Device.current`)

Some parts of the library will require refactoring since some variables don't fit the description anymore. (eg. `Device.allXSeriesDevices` includes iPhone 11).

@denisenepraunig and I are planning on releasing a 2.2.0 with support for the new devices and apply the refactoring changes later for a 3.0.0 release.

**Comment by OkiRules** [comment]
Have the identifiers come out?

**Comment by Zandor300** [comment]
@OkiRules I discovered the identifiers for the iPhone 11, iPhone 11 Pro, iPhone 11 Pro Max and Apple Watch Series 5 through the Xcode simulator but for some reason, I don't have a simulator for the iPad (7th generation) and I also cannot make one for it. I can also find little about it online... https://theiphonewiki.com also hasn't reported it yet. 

_See https://github.com/devicekit/DeviceKit/pull/200/files#diff-3bd960510b9ade64a3ac2466c1d73ae3R348_

**Comment by bizibizi** [comment]
any news?
