### ISSUE TITLE
Add device Cpu name and clock speed

### ISSUE THREAD

**Issue by draco1544** [devicekit/DeviceKit#271]
Please Add device Cpu name and clock speed

**Comment by kallipigous** [comment]
Yes please.

**Comment by furiosFast** [comment]
that would be a nice feature

**Comment by draco1544** [comment]
> that would be a nice feature 

I have make my own since

**Comment by rursache** [comment]
@draco1544 create a pull request so we can all enjoy it

**Comment by furiosFast** [comment]
> > that would be a nice feature
> 
> I have make my own since

Can you share your code?

**Comment by furiosFast** [comment]
is this lib still maintained?

**Comment by Zandor300** [comment]
> is this lib still maintained?

@furiosFast Yes, we always try to add new devices as quickly as possible when they come out, but the library isn't our main priority since we have other jobs. If you really want this added, you or someone else could try to implement it yourself and contribute through a PR. Otherwise, we would need to have spare time available to implement new features.
