### ISSUE TITLE
PhaseScriptExecution failed with python2.7

### ISSUE THREAD

**Issue by oTranAnhMinh** [devicekit/DeviceKit#310]
Hello,

I'm having the problem that Xcode 13.3 can't build on mac os 12.3
Please check soon.

Thank you

**Comment by Zandor300** [comment]
A fix for this is already in #308 which will be released in a new update soon. This is because Apple probably stopped shipping Python 2 with macOS Monterey 12.3.

The fix is to change the first line in `Utils/gyb` from `python2.7` to `python3`:
https://github.com/devicekit/DeviceKit/blob/3afdc46b439b27e3ca1d22c2b97480283b7699f2/Utils/gyb#L1
